### ISSUE TITLE
Error message box is visible even without error

### ISSUE THREAD

**Issue by theshubhagrwl** [guptasajal411/bookshelfly#20]
**Description** 
On the login page, a box in red colour which is probably for error message is visible all the time.
![image](https://user-images.githubusercontent.com/37265683/133717524-bfc7de31-9f3b-4429-9800-3a7c316a0b5f.png)

**Comment by guptasajal411** [comment]
Thank you for trying out Bookshelfly! I will try to fix this bug ASAP 💥

**Comment by guptasajal411** [comment]
This issue is fixed now, for **[login](https://try-bookshelfly.herokuapp.com/login)** and **[register](https://try-bookshelfly.herokuapp.com/register)** page too 🚀
![image](https://user-images.githubusercontent.com/70312106/133730770-9ef3d98b-695b-45ee-9ef9-5f1f5d0851c0.png)
