### ISSUE TITLE
feat: Add a feature for user to request a book

### ISSUE THREAD

**Issue by bhargav794** [guptasajal411/bookshelfly#22]
**Is your feature request related to a problem? Please describe.**
the number of books a library can hold is limited so add a feature that can allow users to request books that are not available in the library. We can add this request button to the navigation bar or footer

**Describe the solution you'd like**
The solution I can think of is to create a form that can collect the name of the author and book requested by the user.

**Comment by guptasajal411** [comment]
Thats a good idea, @bhargav794, I will make a custom route for adding new books to the library. Thanks!
